apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: credit_risk
    user: credit_risk
    secureJsonData:
      password: "${POSTGRES_PASSWORD}"
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false
    editable: true
